services:
  trendlapse-api-{COLOR}:
    image: trendlapse:latest
    container_name: trendlapse-container-{COLOR}
    ports:
      - "{PORT}:8080"
    environment:
      - TZ=Asia/Seoul
    env_file:
      - .env.runtime
    network_mode: bridge
