package io.github.hamsteak.trendlapse.global.error;

public enum DomainError {
    INVALID_USERNAME,
    DUPLICATE_USERNAME,
    INVALID_PASSWORD,
    INVALID_EMAIL,
    MEMBER_NOT_FOUND,
    LOGIN_FAILED,
    SNAPSHOT_NOT_FOUND,
    SNAPSHOT_REPORT_NOT_FOUND,
    SNAPSHOT_REPORT_ALREADY_EXISTS,
    PROMPT_NOT_FOUND,
}
